<p style="font-family: Arial; font-size:3em;color:black;"> Lab 1 </p>

Students name in this Group:

In [3]:
# importing numpy
import numpy as np

In [4]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
arr1 = np.array([1,2,3,5,0])
print(arr1.all())

False


In [5]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.
arr2 = np.array([3,-1,3,7,2])
print(arr2.any())

True


In [6]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.
arr3 = np.array([0, 0, 0, 0])
print(arr3.any())

False


In [7]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.
arr4 = np.array([56, -2, -7])
print(arr4.nbytes)

12


In [8]:
# Create a numpy array with 10 zeros and print the array.
arr0s = np.zeros(10)
print(arr0s)

# Create a numpy array with 6 ones and print the array.
arr1s = np.ones(6)
print(arr1s)

# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
arr3s = np.full(12, 3)
print(arr3s)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[3 3 3 3 3 3 3 3 3 3 3 3]


In [12]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
arr8to20 = np.arange(8, 21, 1)
print(arr8to20)

# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method
arr8to20_even = np.arange(8, 21, 2)
print(arr8to20_even)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 8 10 12 14 16 18 20]


In [28]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
MEAN = 2
STD = 0.5
arr100rand = np.random.normal(MEAN, STD, 100)
print("---100---")
print("Mean:",arr100rand.mean())
print("Max:",arr100rand.max())
print("Min:",arr100rand.min())
print("Std:",arr100rand.std())
# print("------")

# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
arr1000rand = np.random.normal(MEAN, STD, 1000)
print("---1000---")
print("Mean:",arr1000rand.mean())
print("Max:",arr1000rand.max())
print("Min:",arr1000rand.min())
print("Std:",arr1000rand.std())
# print("------")

# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
arr1000000rand = np.random.normal(MEAN, STD, 1000000)
print("---1000000---")
print("Mean:",arr1000000rand.mean())
print("Max:",arr1000000rand.max())
print("Min:",arr1000000rand.min())
print("Std:",arr1000000rand.std())
# print("------")

# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?
# They are different.

---100---
Mean: 2.028618304460676
Max: 3.7902889512137286
Min: 0.7178629073909879
Std: 0.5113695790030361
---1000---
Mean: 1.9809313870402654
Max: 3.34330398212506
Min: -0.28748707545741725
Std: 0.5022412850912168
---1000000---
Mean: 2.0002140581180443
Max: 4.44362482581624
Min: -0.5166326000042925
Std: 0.4996810979725482
